--- 
title: "Tópicos de Finanças com R"
author: "Sillas Gonzaga e Wilson Freitas"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
lot: yes
lof: yes
graphics: yes
colorlinks: yes
description: "Este livro é sobre programação em R aplicada a finanças. Como o R pode ser utilizado no tratamento de dados financeiros, nas análises financeiras e nos cálculos, modelos e simulações de investimentos."
---

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

# Boas-vindas {-}

Tópicos de Finanças com R tenta aproximar o mundo financeiro da linguagem de programação R.
O mercado financeiro é um parque de diversões para profissionais com interesse em programação e em análise de dados.
Há um grande volume de dados disponível online onde qualquer um pode ter acesso e realizar análises.
Infelizmente a análise de dados financeiros não é trivial, é necessário algum conhecimento do problema para entrar nesse mundo, mas isso não é diferente de qualquer outra area do conhecimento.
Este material tenta começar a preencher este hiato.
Trazemos aqui fundamentais para o estudo de finanças e análise de dados, como: estruturas de dados para processamento, onde conseguir os dados, visualização de dados e alguns modelos.
Há diversos exercícios para tornar a jornada o mais aplicada possível.
Esperamos que aproveitem o conteúdo e boas análises.

## Sobre os instrutores {-}

### Sillas Gonzaga {-}

Sillas é sou apaixonado pelo R. Pratica essa linguagem desde 2014 e, desde então, criou o blog chamado [Paixão por Dados](http://sillasgonzaga.com/), já ministrou palestras sobre sua carreira com R e já publicou 4 pacotes R.

### Wilson Freitas {-}

Wilson Freitas é pai, padeiro amador e corredor de rua. Profissionalmente trabalha como Quant (especialista em modelagem quantitativa em finanças) no mercado financeiro desde 2007, onde passou por diversas instituições (Itaú, B3, ModalMais, etc.). Gosta de programar quando não está correndo nem fazendo pão e sempre contribuiu com o software livre desenvolvendo pacotes para as linguagens de programação e escrevendo posts no seu blog. Mantém uma conta ativa no Github ([\@wilsonfreitas](https://github.com/wilsonfreitas)) com mais de 50 repositórios de sua autoria.